version: "3.7"
services:
  backend:
    image: ${DOCKER_IMAGES_PREFIX}-backend:${CRUSHBACK_VERSION}
    restart: unless-stopped
    build:
      context: backend/
      args:
        - HTTPS_PROXY
    environment:
      - DJANGO_SETTINGS_MODULE
      - CRUSHBACK_SECRET_KEY
      - CRUSHBACK_DB_USER
      - CRUSHBACK_DB_PASSWORD
      - CRUSHBACK_DB_NAME
      - CRUSHBACK_DB_HOST
      - CRUSHBACK_DB_PORT
      # Environment variables used by tests
      - CRUSHBACK_TELEGRAM_CLIENT1_API_ID
      - CRUSHBACK_TELEGRAM_CLIENT1_API_HASH
      - CRUSHBACK_TELEGRAM_CLIENT1_SESSION_STRING
    volumes:
      - backend_static_files:/app/static/
    ports:
      - "8000:80"
    depends_on:
      - database
  telegrambot:
    image: ${DOCKER_IMAGES_PREFIX}-backend:${CRUSHBACK_VERSION}
    command: bash -c "sleep 2 && ./manage.py telegrambot"
    restart: unless-stopped
    environment:
      - CRUSHBACK_SECRET_KEY
      - CRUSHBACK_DB_USER
      - CRUSHBACK_DB_PASSWORD
      - CRUSHBACK_DB_NAME
      - CRUSHBACK_DB_HOST
      - CRUSHBACK_DB_PORT
      - CRUSHBACK_TELEGRAM_BOT_TOKEN
      - CRUSHBACK_TELEGRAM_PROXY_URL=socks5://socks-proxy:9000
    ports:
      - "9090:9090"
    depends_on:
      - database
      - socks-proxy
  matchfinder:
    image: ${DOCKER_IMAGES_PREFIX}-backend:${CRUSHBACK_VERSION}
    command: bash -c "./manage.py findnewmatches --period 1"
    restart: unless-stopped
    environment:
      - CRUSHBACK_SECRET_KEY
      - CRUSHBACK_DB_USER
      - CRUSHBACK_DB_PASSWORD
      - CRUSHBACK_DB_NAME
      - CRUSHBACK_DB_HOST
      - CRUSHBACK_DB_PORT
      - CRUSHBACK_NEW_CRUSH_MATCH_FREEZE_MINUTES
    depends_on:
      - database
  matchinformer:
    image: ${DOCKER_IMAGES_PREFIX}-backend:${CRUSHBACK_VERSION}
    command: bash -c "./manage.py informmatches --period 1"
    restart: unless-stopped
    environment:
      - CRUSHBACK_SECRET_KEY
      - CRUSHBACK_DB_USER
      - CRUSHBACK_DB_PASSWORD
      - CRUSHBACK_DB_NAME
      - CRUSHBACK_DB_HOST
      - CRUSHBACK_DB_PORT
      - CRUSHBACK_TELEGRAM_BOT_TOKEN
      - CRUSHBACK_TELEGRAM_PROXY_URL=socks5://socks-proxy:9000
    depends_on:
      - database
      - socks-proxy
  socks-proxy:
    image: ictu/sshpass:latest
    command: sh /socks-proxy.sh
    volumes:
      - ./socks-proxy.sh:/socks-proxy.sh:ro
    environment:
      - SOCKS_HOST
      - SOCKS_USER
      - SOCKS_PASS
    ports:
      - "9000"
  database:
    image: postgres:14.6-alpine3.17
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$CRUSHBACK_DB_ROOT_PASSWORD
      - CRUSHBACK_DB_USER
      - CRUSHBACK_DB_PASSWORD
      - CRUSHBACK_DB_NAME
    ports:
      - $DB_PORT_MAPPING
    volumes:
      - ./.db-data/:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  frontend:
    image: ${DOCKER_IMAGES_PREFIX}-frontend:${CRUSHBACK_VERSION}
    build: ./frontend
    environment:
      - API_BASE_URL
    ports:
      - "80:80"
  crushback-metrics:
    image: ${DOCKER_IMAGES_PREFIX}-metrics:${CRUSHBACK_VERSION}
    build: ./business-metrics
    ports:
      - "9399:9399"

volumes:
  backend_static_files:
