version: "3.7"
services:
  backend:
    image: ${DOCKER_IMAGES_PREFIX}-backend:${CRUSHBACK_VERSION}
    restart: unless-stopped
    build: backend/
    environment:
      - DJANGO_SETTINGS_MODULE
      - CRUSHBACK_SECRET_KEY
      - RECAPTCHA_SERVER_KEY
      - CRUSHBACK_DB_USER
      - CRUSHBACK_DB_PASSWORD
      - CRUSHBACK_DB_NAME
      - CRUSHBACK_DB_HOST
      - CRUSHBACK_DB_PORT
      - CRUSHBACK_TELEGRAM_BOT_TOKEN
      - CRUSHBACK_TELEGRAM_PROXY_URL
      # Environment variables used by tests
      - CRUSHBACK_TELEGRAM_CLIENT1_API_ID
      - CRUSHBACK_TELEGRAM_CLIENT1_API_HASH
      - CRUSHBACK_TELEGRAM_CLIENT1_SESSION_STRING
    volumes:
      - backend_static_files:/app/static/
    ports:
      - "8000:80"
    depends_on:
      - database
  database:
    image: postgres:14.6-alpine3.17
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$CRUSHBACK_DB_ROOT_PASSWORD
      - CRUSHBACK_DB_USER
      - CRUSHBACK_DB_PASSWORD
      - CRUSHBACK_DB_NAME
    ports:
      - $DB_PORT_MAPPING
    volumes:
      - ./.db-data/:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  frontend:
    image: ${DOCKER_IMAGES_PREFIX}-frontend:${CRUSHBACK_VERSION}
    build: ./frontend
    environment:
      - API_BASE_URL
    ports:
      - "80:80"

volumes:
  backend_static_files:
