#!/bin/bash
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${CRUSHBACK_DB_USER} WITH ENCRYPTED PASSWORD '${CRUSHBACK_DB_PASSWORD}';
    CREATE DATABASE ${CRUSHBACK_DB_NAME};
    ALTER USER ${CRUSHBACK_DB_USER} CREATEDB;
EOSQL
