#!/bin/bash
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${DJANGO_REACT_TEMPLATE_DB_USER} WITH ENCRYPTED PASSWORD '${DJANGO_REACT_TEMPLATE_DB_PASSWORD}';
    CREATE DATABASE ${DJANGO_REACT_TEMPLATE_DB_NAME};
    \connect ${DJANGO_REACT_TEMPLATE_DB_NAME};
    CREATE SCHEMA ${DJANGO_REACT_TEMPLATE_DB_SCHEMA} AUTHORIZATION ${DJANGO_REACT_TEMPLATE_DB_USER};
    ALTER ROLE ${DJANGO_REACT_TEMPLATE_DB_USER} SET client_encoding TO 'utf8';
    ALTER ROLE ${DJANGO_REACT_TEMPLATE_DB_USER} SET default_transaction_isolation TO 'read committed';
    ALTER ROLE ${DJANGO_REACT_TEMPLATE_DB_USER} SET timezone TO 'UTC';
EOSQL
