# Default values for crushback.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secretKey: dummy
recaptchaServerKey: dummy
djangoSettingsModule: backend.settings-production
matchFinderPeriodSeconds: 300

replicaCount: 1
image:
  repository: emranbm/crushback-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
resources:
  cpu: 400m
  memory: 128Mi
  ephemeral-storage: 200Mi

database:
  host: postgresql
  port: 5432
  name: crushback_db
  user: root
  password: dummy

backup:
  image: ianneub/pg-dump-to-s3:latest
  schedule: "0 5 * * *"
  s3:
    endpoint: https://crushback.s3.ir-thr-at1.arvanstorage.ir
    accessKey: dummy
    secretKey: dummy
  restore:
    create: false # Make true to generate job from template and delete -> reapply it manually (by kubectl apply)
    backupFilename: latest.sql

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }
