apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "crushback-backend.fullname" . }}-backup-cronjob
  labels:
  {{- include "crushback-backend.labels" . | nindent 4 }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ include "crushback-backend.fullname" . }}-backup-job
              image: {{ .Values.backup.image }}
              imagePullPolicy: IfNotPresent
              env:
                - name: CRUSHBACK_DB_HOST
                  value: "{{ .Values.database.host }}"
                - name: CRUSHBACK_DB_PORT
                  value: "{{ .Values.database.port }}"
                - name: CRUSHBACK_DB_NAME
                  value: "{{ .Values.database.name }}"
                - name: CRUSHBACK_DB_USER
                  value: "{{ .Values.database.user }}"
                - name: CRUSHBACK_DB_PASSWORD
                  value: "{{ .Values.database.password }}"
                - name: AWS_ACCESS_KEY_ID
                  value: "{{ .Values.backup.s3.accessKey }}"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "{{ .Values.backup.s3.secretKey }}"
                - name: S3_ENDPOINT_URL
                  value: "{{ .Values.backup.s3.endpoint }}"
              command: ["bash"]
              args:
                - -c
                - |
                  export PGPASSWORD="$CRUSHBACK_DB_PASSWORD" &&
                  pg_dump --file /tmp/backup.sql --host $CRUSHBACK_DB_HOST \
                    --port $CRUSHBACK_DB_PORT --username $CRUSHBACK_DB_USER --verbose \
                    --encoding "UTF8" --clean $CRUSHBACK_DB_NAME &&
                  day_of_month=$(TZ=Asia/Tehran date +%d) &&
                  aws s3 --endpoint $S3_ENDPOINT_URL cp /tmp/backup.sql s3://crushback/backups/${day_of_month}_of_month.sql &&
                  aws s3 --endpoint $S3_ENDPOINT_URL cp /tmp/backup.sql s3://crushback/backups/latest.sql
  schedule: "{{ .Values.backup.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
