apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crushback-backend.fullname" . }}-match-checker
  labels:
    crsuhback-service: match-checker
spec:
  replicas: 1 # Hardcoded to prevent concurrency issues.
  selector:
    matchLabels:
      crsuhback-service: match-checker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        crsuhback-service: match-checker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-match-finder
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - python
            - manage.py
            - findnewmatches
            - --period
            - "{{ .Values.matchFinderPeriodSeconds }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
            {{- toYaml .Values.resources | nindent 14 }}
            requests:
          {{- toYaml .Values.resources | nindent 14 }}
          env:
            - name: CRUSHBACK_SECRET_KEY
              value: "{{ .Values.secretKey }}"
            - name: DJANGO_SETTINGS_MODULE
              value: "{{ .Values.djangoSettingsModule }}"
            - name: CRUSHBACK_DB_HOST
              value: "{{ .Values.database.host }}"
            - name: CRUSHBACK_DB_PORT
              value: "{{ .Values.database.port }}"
            - name: CRUSHBACK_DB_NAME
              value: "{{ .Values.database.name }}"
            - name: CRUSHBACK_DB_USER
              value: "{{ .Values.database.user }}"
            - name: CRUSHBACK_DB_PASSWORD
              value: "{{ .Values.database.password }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
