apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "crushback-backend.fullname" . }}-match-finder
  labels:
    crsuhback-service: match-finder
spec:
  schedule: "{{ .Values.matchFinderSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}-match-finder
              securityContext:
              {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command:
                - python
                - -u
                - manage.py
                - findnewmatches
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                limits:
                {{- toYaml .Values.resources | nindent 18 }}
                requests:
              {{- toYaml .Values.resources | nindent 18 }}
              env:
                - name: CRUSHBACK_SECRET_KEY
                  value: "{{ .Values.secretKey }}"
                - name: DJANGO_SETTINGS_MODULE
                  value: "{{ .Values.djangoSettingsModule }}"
                - name: CRUSHBACK_DB_HOST
                  value: "{{ .Values.database.host }}"
                - name: CRUSHBACK_DB_PORT
                  value: "{{ .Values.database.port }}"
                - name: CRUSHBACK_DB_NAME
                  value: "{{ .Values.database.name }}"
                - name: CRUSHBACK_DB_USER
                  value: "{{ .Values.database.user }}"
                - name: CRUSHBACK_DB_PASSWORD
                  value: "{{ .Values.database.password }}"
          {{- with .Values.nodeSelector }}
          nodeSelector:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
  {{- toYaml . | nindent 12 }}
  {{- end }}
