apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crushback-telegrambot.fullname" . }}
  labels:
    {{- include "crushback-telegrambot.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "crushback-telegrambot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "crushback-telegrambot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-bot
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - {{ .Values.image.command }}
          args:
            {{- toYaml .Values.image.args | nindent 12 }}
          resources:
            requests:
              {{- toYaml .Values.resources | nindent 14 }}
            limits:
              {{- toYaml .Values.resources | nindent 14 }}
          env:
            - name: CRUSHBACK_SECRET_KEY
              value: "{{ .Values.secretKey }}"
            - name: CRUSHBACK_DB_HOST
              value: "{{ .Values.database.host }}"
            - name: CRUSHBACK_DB_PORT
              value: "{{ .Values.database.port }}"
            - name: CRUSHBACK_DB_NAME
              value: "{{ .Values.database.name }}"
            - name: CRUSHBACK_DB_USER
              value: "{{ .Values.database.user }}"
            - name: CRUSHBACK_DB_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: CRUSHBACK_TELEGRAM_BOT_TOKEN
              value: {{ .Values.telegramBotToken }}
            - name: CRUSHBACK_TELEGRAM_PROXY_URL
              value: {{ .Values.proxyUrl }}
            - name: CRUSHBACK_TELEGRAMBOT_METRICS_PORT
              value: {{ .Values.metricsPort }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
              protocol: TCP
        - name: {{ .Chart.Name }}-match-informer
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - python
            - -u
            - manage.py
            - informmatches
            - --period
            - "{{ .Values.matchInformerPeriodSeconds }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
            {{- toYaml .Values.resources | nindent 14 }}
            requests:
          {{- toYaml .Values.resources | nindent 14 }}
          env:
            - name: CRUSHBACK_SECRET_KEY
              value: "{{ .Values.secretKey }}"
            - name: CRUSHBACK_DB_HOST
              value: "{{ .Values.database.host }}"
            - name: CRUSHBACK_DB_PORT
              value: "{{ .Values.database.port }}"
            - name: CRUSHBACK_DB_NAME
              value: "{{ .Values.database.name }}"
            - name: CRUSHBACK_DB_USER
              value: "{{ .Values.database.user }}"
            - name: CRUSHBACK_DB_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: CRUSHBACK_TELEGRAM_BOT_TOKEN
              value: {{ .Values.telegramBotToken }}
            - name: CRUSHBACK_TELEGRAM_PROXY_URL
              value: {{ .Values.proxyUrl }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
