# Default values for crushback-telegrambot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


secretKey: dummy
telegramBotToken: dummy
proxyUrl: "socks5://socks-proxy:8123"
matchInformerPeriodSeconds: 300
metricsPort: 9090
maxCrushes: 3
crushMatchFreezeMinutes: 15

replicaCount: 1

image:
  repository: emranbm/crushback-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  command: python
  args:
    - ./manage.py
    - telegrambot

database:
  host: postgresql
  port: 5432
  name: crushback_db
  user: root
  password: dummy

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  cpu: 150m
  memory: 128Mi
  ephemeral-storage: 100Mi

service:
  type: ClusterIP
  port: 9090

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
