# Generated by Django 4.1.6 on 2023-02-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_make_user_telegram_info_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
