# Generated by Django 4.1.6 on 2023-02-20 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_crush'),
    ]

    operations = [
        migrations.AddField(
            model_name='crush',
            name='crusher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='crushes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
