# Generated by Django 4.1.6 on 2023-04-02 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_crush_duplicate_crush_preventer'),
    ]

    operations = [
        migrations.AddField(
            model_name='crush',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
