global:
  # Subtracted from Prometheus' scrape_timeout to give us some headroom and prevent Prometheus from
  # timing out first.
  scrape_timeout_offset: 500ms
  # Minimum interval between collector runs: by default (0s) collectors are executed on every scrape.
  min_interval: 60s
  # Maximum number of open connections to any one target. Metric queries will run concurrently on
  # multiple connections.
  max_connections: 3
  # Maximum number of idle connections to any one target.
  max_idle_connections: 3

# The target to monitor and the list of collectors to execute on it.
target:
  # Data source name always has a URI schema that matches the driver name. In some cases (e.g. MySQL)
  # the schema gets dropped or replaced to match the driver expected DSN format.
  data_source_name: 'postgres://$CRUSHBACK_DB_USER:$CRUSHBACK_DB_PASSWORD@$CRUSHBACK_DB_HOST:$CRUSHBACK_DB_PORT/$CRUSHBACK_DB_NAME?sslmode=disable'
  collectors:
    - main_collector

  # Collectors (referenced by name) to execute on the target.
collectors:
  - collector_name: main_collector
    metrics:
      - metric_name: crushback_users_total
        type: gauge
        help: 'Total number of users registered at Crushback.'
        key_labels: [] # Populated from the corresponding column of each row.
        static_labels: {}
        values: [count]
        query: "select count(*) as count from main_user"
      - metric_name: crushback_crushes_total
        type: gauge
        help: 'Total number of distinct Crushes present at Crushback.'
        key_labels: [] # Populated from the corresponding column of each row.
        static_labels: {}
        values: [count]
        query: "select count(distinct telegram_username) as count from main_crush"
      - metric_name: crushback_matchedrecords_total
        type: gauge
        help: 'Total number of MatchedRecords.'
        key_labels: # Populated from the corresponding column of each row.
          - informed
        static_labels: {}
        values: [count]
        query: "select count(*) as count, informed from main_matchedrecord group by informed"
