apiVersion: v1
kind: Service
metadata:
  name: {{ include "crushback.fullname" . }}-backend
  labels:
    {{- include "crushback.labels.backend" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: backend
      protocol: TCP
      name: http
  selector:
    {{- include "crushback.selectorLabels.backend" . | nindent 4 }}
