apiVersion: v1
kind: Service
metadata:
  name: {{ include "crushback.fullname" . }}
  labels:
    {{- include "crushback.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crushback.selectorLabels" . | nindent 4 }}
