# Default values for telegrambot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


telegramBotToken: dummy
proxyUrl: "socks5://socks-proxy:8123"

replicaCount: 1

image:
  repository: emranbm/crushback-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  cpu: 150m
  memory: 128Mi
  ephemeral-storage: 100Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
