# Default values for crushback.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  secretKey: dummy
  recaptchaServerKey: dummy
  djangoSettingsModule: backend.settings-production
  replicaCount: 1
  image:
    repository: emranbm/crushback-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "master-135368b5194a750f8ae93b8f75a5a0c957d9e9b6"
  resources:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 200Mi

frontend:
  apiBaseUrl: "https://api.crushback.net"
  replicaCount: 1
  image:
    repository: emranbm/crushback-frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "master-135368b5194a750f8ae93b8f75a5a0c957d9e9b6"
  resources:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 200Mi

database:
  host: postgresql
  port: 5432
  name: crushback_db
  user: root
  password: dummy

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }
