# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prometheusConfig: |
  global:
    scrape_interval: 15s
    external_labels:
      monitor: 'crushback-cluster'

  scrape_configs:
    # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
    - job_name: 'prometheus'
      static_configs:
        - targets: [ 'cluster-metrics' ]

replicaCount: 1

image:
  repository: prom/prometheus
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2.42.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  cpu: 200m
  memory: 256Mi
  ephemeral-storage: 150Mi
  storage: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
