apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.config.configMapName" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.prometheusConfigs | nindent 2 }}
