apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    {{ include "prometheus.labels" . }}
  name: {{ include "prometheus.fullname" }}-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.storage }}
  storageClassName: standard