apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crushback-metrics.configMapName" . }}
  labels:
    {{- include "crushback-metrics.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.sqlExporterConfig) . | nindent 2 }}
