---
name: Master Workflow
on:
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Inflate the version variable
        run: |
          echo "CRUSHBACK_VERSION=master-${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_REGISTRY_TOKEN }} | docker login -u ${{ vars.DOCKER_REGISTRY_USER }} --password-stdin ${{ vars.DOCKER_REGISTRY_HOST }}
      - name: Build images
        run: docker-compose build --parallel
      - name: Run unit tests
      # TODO: Instead of blind sleep, check DB health.
        run: docker-compose run backend bash -c "sleep 1.5 && ./manage.py test"
      - name: Push images to the registry
        run: docker-compose push
  deploy:
    runs-on: ubuntu-20.04
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Kube config
        run: >
          KUBE_API_SERVER="${{ vars.KUBE_API_SERVER }}"
          KUBE_NAMESPACE="${{ vars.KUBE_NAMESPACE }}"
          KUBE_API_TOKEN="${{ secrets.KUBE_API_TOKEN }}"
          ./.github/scripts/setup-kubectl.sh
      - run: >
          helm upgrade -i crushback
          --set backend.image.tag="master-${GITHUB_SHA}"
          --set backend.secretKey="${{ secrets.CRUSHBACK_SECRET_KEY }}"
          --set backend.recaptchaServerKey="${{ secrets.RECAPTCHA_SERVER_KEY }}"
          --set database.password="${{ secrets.POSTGRES_ROOT_PASSWORD }}"
          k8s/helm/crushback/
