---
name: Restore database backup
on:
  workflow_dispatch:
    inputs:
      backup_filename:
        description: Backup file name (e.g. day_of_month_07.sql)
        required: false
        default: latest.sql
jobs:
  restore-backup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Kube config
        run: >
          KUBE_API_SERVER="${{ vars.KUBE_API_SERVER }}"
          KUBE_NAMESPACE="${{ vars.KUBE_NAMESPACE }}"
          KUBE_API_TOKEN="${{ secrets.KUBE_API_TOKEN }}"
          ./.github/scripts/setup-kubectl.sh
      - name: Restore backup
        run: >
          ./.github/scripts/restore-backup.sh
            "${{ secrets.POSTGRES_ROOT_PASSWORD }}"
            "${{ secrets.DROPBOX_TOKEN }}"
            "${{ github.event.inputs.backup_filename }}"
